doc-warnings: false
use: flask
max-line-length: 120
ignore-paths:
  - psa_connectedcar
  - test
pep8:
  disable:
    - E722
pyflakes:
  disable:
   - F401
pylint:
  disable:
    - fixme
    - C0114
    - C0115
    - C0116
    - W0603
    - I0011
    - W0511

