# coding: utf-8

"""
    Groupe PSA Connected Car - WEB API B2C

    *PSA B2C Connected Car API*  # Introduction This is the description of the *Groupe PSA Connected Car V2 API*. The speccification is  is based on **OpenAPI Specification version 3** and can be displayed via [ReDoc](https://github.com/Rebilly/ReDoc)a or [Swagger](http://swagger.io).   This API allows applications to fetch data from the connected Vehicles data platform. # Authentication PSA Connected Car APIs uses the [OAuth 2.0](https://tools.ietf.org/html/rfc6749) protocol for authentication and Authorization. any application require a valid [Access Token](https://tools.ietf.org/html/rfc6749#section-1.4) to access to user data. # Errors   Error codes returned by all REST APIs comply with the standard. Nevertheless, PSA Services (callers) need to have more complete data structures (even when the answer is not Http-OK) to better detail the type of error by providing application code, message and a debugging code(for investigation purposes). The http code of the response is managed by the protocol itself (in the header).      **Errors are  returned as a generic error response:**    * ```xError``` object model.       # noqa: E501

    OpenAPI spec version: 4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MonitorRef(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'MonitorRefLinks',
        'monitor_id': 'MonitorId'
    }

    attribute_map = {
        'links': '_links',
        'monitor_id': 'monitorId'
    }

    def __init__(self, links=None, monitor_id=None):  # noqa: E501
        """MonitorRef - a model defined in Swagger"""  # noqa: E501

        self._links = None
        self._monitor_id = None
        self.discriminator = None

        if links is not None:
            self.links = links
        if monitor_id is not None:
            self.monitor_id = monitor_id

    @property
    def links(self):
        """Gets the links of this MonitorRef.  # noqa: E501


        :return: The links of this MonitorRef.  # noqa: E501
        :rtype: MonitorRefLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this MonitorRef.


        :param links: The links of this MonitorRef.  # noqa: E501
        :type: MonitorRefLinks
        """

        self._links = links

    @property
    def monitor_id(self):
        """Gets the monitor_id of this MonitorRef.  # noqa: E501


        :return: The monitor_id of this MonitorRef.  # noqa: E501
        :rtype: MonitorId
        """
        return self._monitor_id

    @monitor_id.setter
    def monitor_id(self, monitor_id):
        """Sets the monitor_id of this MonitorRef.


        :param monitor_id: The monitor_id of this MonitorRef.  # noqa: E501
        :type: MonitorId
        """

        self._monitor_id = monitor_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MonitorRef, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MonitorRef):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
